theme: minima
title: Reecebook
author: thereeceshow
email: reece@reecewalter.com
description: > # this means to ignore newlines until "baseurl:"
  The Life and Times of Reece Walter

# social links
twitter_username: ReeceWalter
github_username:  thereeceshow

show_excerpts: true # set to false to remove excerpts on the homepage
